### ISSUE TITLE
Ubah password semua mahasiswa

### ISSUE THREAD

**Issue by addingama** [addingama/siakad-lptnu-issues#4]
Jalankan sql berikut untuk mengubah password semua mahasiswa

```
UPDATE sc_user set "password" = md5(username), hints = username from sc_userrole WHERE sc_userrole.koderole='M' and sc_user.userid = sc_userrole.userid;
```

**Comment by pribbadi** [comment]
hasil dari query tersebut nantinya username dan password menggunakan data apa Pak?

**Comment by pribbadi** [comment]
Maaf saya newbie sumbang solusi lain. Jadi saya coba secara full query karena berawal dari nyoba nyari lokasi tabel di schema. 
Hasil dari query adalah menyamakan password login mahasiswa dengan nim-nya.

```
UPDATE gate.sc_user 
set "password" = md5(username), hints = username 
from gate.sc_userrole 
WHERE gate.sc_userrole.koderole='M' 
and gate.sc_user.userid = gate.sc_userrole.userid;
```
