### ISSUE TITLE
Solusi masalah data tidak bisa diedit via aplikasi padahal import data via pgadmin berhasil (sesuai timit)

### ISSUE THREAD

**Issue by pribbadi** [addingama/siakad-lptnu-issues#5]
Saat migrasi saya menggunakan prosedur yang ada di **timit** (nggak usah saya tampilin linknya ya, pengguna lptnu pasti tahu), tetapi ada kendala yaitu saat edit/hapus data ( kasus saya pada tabel akademik.ak_matakuliah dan akademik.ak_kurikulum).
Langkah saya clear dengan:
1. jika masih ada histori pada akademik.hi_histmatakuliah maka datanya perlu dihapus.
2. Sementara membuat 2 file hasil dari ATM timit dan sudah saya uji coba nggak ada masalah (Alhamdulillah). file saya lampirkan.
2.a. File Import Matakuliah [Unugiri Template Import Matakuliah.xlsx](https://github.com/addingama/siakad-lptnu-issues/files/5360964/Unugiri.Template.Import.Matakuliah.xlsx)
2.b. File Import Kurikulum Prodi 
[Unugiri Import Kurikulum Prodi.xlsx](https://github.com/addingama/siakad-lptnu-issues/files/5360966/Unugiri.Import.Kurikulum.Prodi.xlsx)

NB: karena keburu waktu, jadi saya gak fokus pada oprek coding/ sebisa mungkin tidak mlajari coding secara mendalam pada setiap masalah (alias banyak memanfaatkan intuisi hehe).
Semoga nantinya bisa update file-file import yang lainnya, thanks.

**Comment by addingama** [comment]
untuk coding nya memang sy juga masih belum bisa paham, tp paling tidak issue2 nya bisa kita catat disini

Terima kasih pak @pribbadi 👍
